"Resources"
{
	"materials/hud/leaderboard_class_boss_hollowhead.vmt"	"file"
	"materials/hud/leaderboard_class_boss_hollowhead.vtf"	"file"
	"materials/hud/leaderboard_class_boss_hollowhead_giant.vmt"	"file"
	"materials/hud/leaderboard_class_boss_icarus.vmt"	"file"
	"materials/hud/leaderboard_class_boss_icarus.vtf"	"file"
	"materials/hud/leaderboard_class_boss_icarus_giant.vmt"	"file"
	"materials/hud/leaderboard_class_boss_ignus.vmt"	"file"
	"materials/hud/leaderboard_class_boss_ignus.vtf"	"file"
	"materials/hud/leaderboard_class_boss_ignus_giant.vmt"	"file"
	"materials/hud/leaderboard_class_boss_ironhelm.vmt"	"file"
	"materials/hud/leaderboard_class_boss_ironhelm.vtf"	"file"
	"materials/hud/leaderboard_class_boss_ironhelm_giant.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_grapple.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_grapple.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_grapple_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_uber_giant.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_flareheal.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_flareheal.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_flareheal_giant.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_manmelter.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_manmelter.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_manmelter_giant.vmt"	"file"
	"materials/hud/leaderboard_class_scout_shortstop_giant.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_mangler.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_mangler.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_mangler_giant.vmt"	"file"
}