"Resources"
{
	"materials/hud/leaderboard_class_demo_clusterbomb.vmt"	"file"
	"materials/hud/leaderboard_class_demo_clusterbomb.vtf"	"file"
	"materials/hud/leaderboard_class_demo_clusterbomb_giant.vmt"	"file"
	"materials/hud/leaderboard_class_demo_loosecannon.vmt"	"file"
	"materials/hud/leaderboard_class_demo_loosecannon.vtf"	"file"
	"materials/hud/leaderboard_class_demo_loosecannon_giant.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_deflector_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_blast.vmt"	"file"
	"materials/hud/leaderboard_class_medic_blast.vtf"	"file"
	"materials/hud/leaderboard_class_medic_blast_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_bullet.vmt"	"file"
	"materials/hud/leaderboard_class_medic_bullet.vtf"	"file"
	"materials/hud/leaderboard_class_medic_bullet_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_fire.vmt"	"file"
	"materials/hud/leaderboard_class_medic_fire.vtf"	"file"
	"materials/hud/leaderboard_class_medic_fire_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf.vtf"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_uber.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_uber.vtf"	"file"
	"materials/hud/leaderboard_class_medic_shield_uber_giant.vmt"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vmt"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vtf"	"file"
	"materials/hud/leaderboard_class_scout_sunstick_giant.vmt"	"file"
}